<?php
require __DIR__.'/fixture.php';
$root=dirname(__DIR__);require_quicknav($root);
$GLOBALS['manager']->items=items();
$scripts=(new ASQN_Advanced_Scripts_Adapter())->scripts();
expect(!isset($scripts[2]['code']),'Adapter must not expose code');
$nav=new ASQN_Navigation_Builder($scripts);
expect($nav->count()===4,'Folders excluded from count');expect($nav->blocked($scripts[2]),'Inactive direct ancestor');expect($nav->blocked($scripts[5]),'Inactive nested ancestor');expect($nav->path($scripts[5])==='Shop / Styles','Complete path');
expect(ASQN_Advanced_Scripts_Adapter::safe_mode(),'Option-based Safe Mode');
define('AS_SAFE_MODE',false);expect(!ASQN_Advanced_Scripts_Adapter::safe_mode(),'False constant overrides true option');
$GLOBALS['meta'][ASQN_Config::key('favorites')]=[2,2,1,999,5,[]];
expect(ASQN_Favorites::ids($scripts)===[2,5],'Favorites remove deleted, folder, duplicate and malformed IDs');
$GLOBALS['blog']=2;expect(ASQN_Favorites::ids($scripts)===[],'Favorites isolated by site');$GLOBALS['blog']=1;
$bar=new FakeBar();$renderer=new ASQN_Admin_Bar_Renderer($nav);$renderer->add_admin_bar_menu($bar);
expect(isset($bar->nodes['asqn-script-2'],$bar->nodes['asqn-folder-script-2'],$bar->nodes['asqn-favorite-script-2']),'Independent IDs for three projections');
expect(strpos($bar->nodes['asqn-script-2']['title'],'&lt;script&gt;')!==false,'Script title escaped');
expect(strpos($bar->nodes['asqn-folder-4-new']['href'],'parent=4')!==false&&strpos($bar->nodes['asqn-folder-4-new']['href'],'edit=0')!==false,'Create inside selected folder');
$renderer->enqueue_admin_bar_styles();expect(isset($GLOBALS['inline']['admin-bar']),'Custom color scheme falls back safely');

$stats=$nav->statistics();expect($stats['total']===4&&$stats['active']===3&&$stats['inactive']===1&&$stats['blocked']===2&&$stats['folders']===2,'Statistics separate saved flags, ancestor blocking and folders');
expect(array_sum($stats['types'])===4,'Type counts account for all snippets');
expect((new ASQN_Navigation_Builder([]))->statistics()['total']===0,'Empty statistics safe');
$GLOBALS['meta'][ASQN_Config::key('preferences')]=['fullscreen'=>true,'counter'=>true];
expect(!array_key_exists('fullscreen',ASQN_Config::preferences()),'Removed fullscreen preference is ignored');
expect(!method_exists($renderer,'adminbar_block_editor_fullscreen')&&!method_exists($renderer,'remove_adminbar_nodes'),'No fullscreen adjustment or WordPress-logo removal');
$html=Deckerweb_Changelog_Renderer_V1::render("== Changelog ==\n\n= 1.2.0-rc2 · 2026-10-01 =\n* Neu: Beispiel `<script>alert(1)</script>`\n* Behoben: Fehler\n\n== Installation ==\nPrivate text");
expect(strpos($html,'<h3>1.2.0-rc2</h3>')!==false&&strpos($html,'ddw-changelog-new')!==false,'HTML changelog version and category');
expect(strpos($html,'<script>')===false&&strpos($html,'<code>&lt;script&gt;')!==false,'Changelog source safely escaped');
expect(strpos($html,'Private text')===false&&strpos($html,'== Changelog ==')===false,'Readme markers and unrelated sections omitted');
define('ASQN_PLUGIN_FILE',$root.'/advanced-scripts-quicknav.php');
ob_start();(new ASQN_Settings())->page();$page=ob_get_clean();
expect(strpos($page,'data-asqn-favorite-card="2"')!==false&&strpos($page,'edit=2')!==false,'Favorites cards link to native editor');
expect(strpos($page,'ddw-changelog-release')!==false&&strpos($page,'<pre')===false,'Modal renders structured HTML');
expect(strpos($page,'name="fullscreen"')===false&&strpos($page,'asqn-stat-total')!==false,'Settings show statistics and omit fullscreen toggle');
$GLOBALS['permission']=false;$denied=new FakeBar();$renderer->add_admin_bar_menu($denied);expect(!$denied->nodes,'Unauthorized user receives no toolbar nodes');$GLOBALS['permission']=true;
$GLOBALS['filters']['ddw/quicknav/as_links']=static function($links){return ['custom'=>['title'=>'Example','url'=>'https://example.test']];};
$GLOBALS['filters']['ddw/quicknav/csn_codelibs']=static function($links){return ['custom'=>['title'=>'Library','url'=>'https://example.test']];};
$filtered=new FakeBar();$renderer->add_admin_bar_menu($filtered);expect(isset($filtered->nodes['asqn-link-custom'],$filtered->nodes['asqn-library-link-custom']),'Filter return values applied with distinct IDs');
define('ASQN_DISABLE_FOOTER','yes');$hidden=new FakeBar();$renderer->add_admin_bar_menu($hidden);expect(!isset($hidden->nodes['asqn-footer'],$hidden->nodes['asqn-links'],$hidden->nodes['asqn-about'])&&isset($hidden->nodes['asqn-libraries']),'Footer disable does not hide library');
define('ASQN_DISABLE_LIBRARY','yes');$hidden=new FakeBar();$renderer->add_admin_bar_menu($hidden);expect(!isset($hidden->nodes['asqn-library'],$hidden->nodes['asqn-libraries']),'Library disable removes entire subtree');
$empty=new FakeBar();(new ASQN_Admin_Bar_Renderer(new ASQN_Navigation_Builder([])))->add_admin_bar_menu($empty);expect(isset($empty->nodes['asqn-active'],$empty->nodes['asqn-inactive']),'Empty collections have safe status nodes');
$many=[];for($i=1;$i<=250;$i++)$many[$i]=['term_id'=>$i,'parent'=>0,'title'=>'Script '.$i,'type'=>'text/css','status'=>true,'location'=>'front','hook'=>''];
$limited=new FakeBar();(new ASQN_Navigation_Builder($many))->statuses($limited);expect(count($limited->nodes)===43,'Status lists bounded with view-all link');
expect(isset($limited->nodes['asqn-active-more']),'Overflow remains reachable');
$cycle=[1=>['term_id'=>1,'parent'=>2,'title'=>'A','type'=>'folder','status'=>true,'location'=>'','hook'=>''],2=>['term_id'=>2,'parent'=>1,'title'=>'B','type'=>'folder','status'=>false,'location'=>'','hook'=>'']];
$cyclic=new ASQN_Navigation_Builder($cycle);expect($cyclic->blocked($cycle[1]),'Cycle-safe ancestor walk');$cyclic->folders(new FakeBar());
echo "Focused release checks passed. Full WordPress integration matrix is deferred.\n";
